### ISSUE TITLE
Grails apps will not deploy to Glassfish 4+

### ISSUE THREAD

**Issue by ddelponte** [grails/grails-async#21]
### Steps to Reproduce

1. Deploy a simple Grails app war file to glassfish 4+
2. Example war file you may use: 
https://drive.google.com/file/d/1m4_tDOQlzk_7fBh3EMV0vQ1Gx8mztiLn/view?usp=sharing

### Expected Behaviour
The war file deploys successfully without error

### Actual Behaviour
The war file does not deploy.  The following error is logged:

```
[2018-05-14T15:00:02.054-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=45 _ThreadName=admin-listener(4)] [timeMillis: 1526328002054] [levelValue: 1000] [[
  Exception while deploying the app [sec-access-issue-0.1] : The lifecycle method [close] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void org.grails.async.factory.future.CachedThreadPoolPromiseFactory.close() throws java.io.IOException] of type [METHOD]
The lifecycle method [close] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void org.grails.async.factory.future.CachedThreadPoolPromiseFactory.close() throws java.io.IOException] of type [METHOD]
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:373)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:381)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessorImpl.java:289)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:217)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:134)

```

### Additional Thoughts

Methods annotated with @PreDestroy should not throw a checked exception.

Taking into account that this is a javax.* annotations and checking the documentation https://docs.oracle.com/javaee/7/api/javax/annotation/PreDestroy.html we can see that methods in the Grails source code not fully following the signature according to the Javadoc, thus we may want to adjust the signatures of the the methods that use `@PreDestroy` annotation by removing the checked exceptions from them.

### Environment Information

- **Operating System**: macOS 10.13.4
- **Grails Version:** 3.3.5
- **JDK Version:** 1.8.0_171
- **Container Version (If Applicable):** Glassfish 4.x, Glassfish 5.x

### Example Application

- https://github.com/xavier-gallofre/sec-access-issue

**Comment by ddelponte** [comment]
The related PR, https://github.com/grails/grails-async/pull/22, has been reviewed and merged.

Closing and marking this issue as `Fixed`
